---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - eventing.knative.dev
  resources:
  - triggers
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - weaver.io
  resources:
  - weaveragents
  - weavernodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weaver.io
  resources:
  - weaveragents/finalizers
  verbs:
  - update
- apiGroups:
  - weaver.io
  resources:
  - weaveragents/status
  - weavernodes/status
  verbs:
  - get
  - patch
  - update
