# This rule is not used by the project weaver itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to weaver.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: weaver
    app.kubernetes.io/managed-by: kustomize
  name: weaveragent-viewer-role
rules:
- apiGroups:
  - weaver.io
  resources:
  - weaveragents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - weaver.io
  resources:
  - weaveragents/status
  verbs:
  - get
