apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: weaver
spec:
  # Using the MT Channel Based Broker
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-br-default-channel
    namespace: knative-eventing
